### ISSUE TITLE
Update build instructions

### ISSUE THREAD

**Issue by kiwec** [secretdataz/BetterFonts#12]
#4. Apply patch file to FontRenderer.java

Should be : 

> patch src/main/java/net/minecraft/client/gui/FontRenderer.java < patch src/main/java/net/minecraft/client/gui/FontRenderer1.7.10.java.patch

Instead of : 

> patch src/main/java/net/minecraft/client/gui/FontRenderer.java < FontRenderer1.7.10.java.patch

**Comment by secretdataz** [comment]
Good catch. I'll change it when I can use my laptop.
